# install the following packages (in this order

.linter
.acp
.typescript


## additional packages that are helpful

 .sort-lines
 .language post-css
 .terminal-plus
 .open-browser-here

### Web development
.pigments



### Getting started

== linter-eslint, use the AirBNB style convention file (.eslintrc)

### check your settings and the settings under packages
. ensure soft wraps is on


### To get multiple cursors
Hold down ctrl key and click with mouse where you want extra cursors
to delete the cursors press esc key.

### Easily comment
ctrl + /

### Modifying your themes and syntax

Other than the normal way to modify to preset themes one can also go to
View | Developer | View in dev mode

then right clikc on inspect element and you get the chrome dev tools to see what classes to change
* Remember * Atom is just a browser. You can then go

File | modify stylesheet and it is a regular less css file which you can modify the settings there.

=== Integrating with Github

. Use Ctrl + alt + z on the file where changes have occured and you can revert to HEAD
same as doing a git checkout in terminal

alt + g, c - use to get the github version hyperlink of the file 
