== Functional programming

Functional programming is not only about composing functions and algebraic data structures — it makes concurrency composable 

=== Monads
A monad is a way to structure computations (like a design pattern) in terms of values and sequences of computations using those values. 
Monads allow the programmer to build up computations using sequential building blocks, which can themselves be
sequences of computations. The monad determines how combined computations form a new computation and frees 
the programmer from having to code the combination manually each time it is required.
.d
<a href="https://wiki.haskell.org/All_About_Monads">Haskell Wiki about Monads</a>


Monads have to satisfy three laws, namely:

1. Law of Associativity
2. Left unit law
3. Right unit law

Monad has this shape here

[source,scala]
----
  trait Monad[A] {
    def map[B](f: A => B): Monad[B]
    def flatmap[B](f: A => Monad[B]): Monad[B]
  }  
----

=== Monoids
 
=== Functors
 
=== Monad transformers 
 
=== Applicative functors

==== Referential transparency

==== Substitution principle

The precise meaning of "being the same" is defined by the property of "operational equivalence"

^^ Parsers and combinators
. A parser is a function that takes a stream of input tokens, and converts them into a format (typically a data structure, 
such as a list or a tree) that is more easily consumed by your application.
. A combinator is simply a higher order function which combines two functions into a new function.
