
System.in represents the keyboard

System.in provides access to raw bytes of data from the input device, which is the keyboard in our example. It is
the job of the InputStreamReader class to take those bytes and convert them into characters in your current character
set. System.in is passed to the InputStreamReader() constructor to create an InputStreamReader object.
InputStreamReader knows about characters, but not about lines. It is the BufferedReader class’s job to detect
line breaks in the input stream, and to enable you to conveniently read a line at a time. BufferedReader also aids
efficiency by allowing physical reads from the input device to be done in different-size chunks than by which your
application consumes the data. This aspect can make a difference when the input stream is a large file rather than the
keyboard.


Functional Interfaces

Lambda expressions allow you to encapsulate functionality and assign to a variable for later use, if desired. Believe
it or not, there is a simplified variation of a lambda expression referred to as a method reference. If a class contains
a method that is derived from the implementation of a functional interface, then that method can be obtained or
“captured” and assigned to a variable for later use. The concept being that the method contains functionality that can
be assigned to a variable of the same type as the functional interface.



The double colon operator is used to indicate a method reference. In this example, a reference to an instance
method of a specific object is used

= Special case pattern (Fowler)

= Cake pattern




