== HTML styling

Three important properties control the space that surrounds each HTML element: 
. padding, 
. margin, and 
. border.

The four values available for padding and margin: -top, -right, -left and -bottom
These four values work like a clock: top, right, bottom, left, and will produce 
the exact same result as using the side-specific padding instructions.

CSS Styling.

Browsers read CSS from top to bottom. That means that, in the event of a conflict, 
the browser will use whichever CSS declaration came last. Except an Id tag which takes precedence
over classes.

== HTML5 video and audio

any sort of open source, free or commercial video encoding software, such as Handbrake 
(free, open source) or Super (free). There are also online video encoding services, 
and you can even upload your video to YouTube, let it encode your video in several resolutions 
and codecs, and use a browser extension such as VideoDownloadHelper (for Firefox) to download the 
video in your chosen formats.

recommended formats are mp4/H264 and in webm formats, and ogg.

= Adding subtitles
Many tools - both free and commercial - are available to add subtitles to a video. 
Most are native applications you need to install on your computer. However, a free and 
very practical tool is available for doing this 100% in a Web browser: http://www.universalsubtitles.org, 
also known as http://www.amara.org.