== JavaScript reference

The purpose of this file is to highlight some of the most used features of Javascript

== Values versus reference types.

Note: “Function” is a reference type.

** JavaScript implements 'duck' typing. Duck typing is a style of dynamic typing in which an object's methods and properties determine the valid semantics, rather than its inheritance from a particular class or implementation of a specific interface. The name of the concept refers to the duck test, attributed to James Whitcomb Riley, which may be phrased as follows:

  "When I see a bird that walks like a duck and swims like a duck and quacks like a duck, I call that bird a duck"

==== Javascript as a language offers two main paradigm which other languages don't always have:

.Prototypal Inheritance (objects without classes, and prototype delegation, aka OLOO Objects Linking to Other Objects), and
.Functional Programming (enabled by lambdas with closure)


All numbers in javascript are treated as 64bit floating point numbers.

There are useful built in functions such as on the following objects.

.Math
.String
.Number

Always use the triple equals operator to remove a lot of confusion from your code.
. ===
. and !==


=== Closures 

a closure is the combination of a function bundled together (enclosed) with 
references to it’s surrounding state (the lexical environment). In JavaScript, 
closures are created every time a function is created, at function creation time.

. a closure gives you access to an outer function’s scope from an inner function.
. To use a closure, simply define a function inside another function and expose it. 
. To expose a function, return it or pass it to another function.
. The inner function will have access to the variables in the outer function scope, even after the outer function has returned.

=== declaring variables

*Let* statement respects block scope
*var* statement respects function scope
*const* varilables have block scope and cannot be changed

NOTE: for all var declarations declare your variables at the top of the function scope to reduce confusion.

The Gotcha with variable declarations and assignment is the oddity that variables declarations are 
hoisted to the top of the current functional scope but not the assignment. So one 
might get typically 'undefined' when one was expecting the initialized variable.



Watch out for implicit global variables.

=== Two ways to delcare functions

1. Function declaration - compiled before all other code runs
2. Function expression - The => symbol represents an arrow pointing to the right, It’s visually saying “use the value
in the parenthesis to do some work in the next block of code that I’m pointing to.”

NOTE: It is important to understand the difference between a function expression, which can be invoked by an IIFE and
a function declaration.

```
let saySomething = (value) => {
console.log(value)
};
```


TIP: A good style convention is to stick with one way of declaring functions and stick with it throughout. 
As function declarations are always 'hoisted' it may be better to use function expressions because you get more
predictable results. Function expressions are never hoisted, additionally they 
play must better with the functional programming paradigm, as they are then just values
which can be passed around (higher order programming).

=== Looping the ES6 way

ES6 introduces some really functional means to loop through Arrays which allows you to
move away from imperative if blocks and break statements.

Array now has the
*some* // since ES5
*every* The exact opposite of some
*forEach* // ES5
*findIndex* // returns the index
*find*      // returns true
*map* // ES5

=== Truthy - Falsy values

Every value in JavaScript is “truthy” except false, null, and undefined. The opposite of “truthy” is “falsy,”
and the aforementioned false, null, and undefined are considered “falsy.”

Falsy values:

. false
. null
. "" (empty string)
. 0
. NaN
. undefined

All other values (including objects and empty arrays) are truthy

*!!* is the way we write “is truthy” in JavaScript.

[source, javascript]
----
const even = (n) =>
  n === 0 || (n !== 1 && even(n - 2))
even(42) //=> true
----

The above code snippet is proof that the && and || are really control flow operators and
not logical operators. The above code would result in a stack overflow exception if both left and
right side expressions were evaluated. Instead it checks the left hand side and if true ends.


### Arrow Functions

TIP: Best Practice: Use Arrow Functions whenever you need to preserve the lexical value of this.

methods which takes an array function.

Function array takes three parameters, the first is mandatory the other two are optional:

function (element, index, array)




isNAN()

String
  .substr
  .substring
  .indexOf
  .split
  .toUppercase
  .toLowercase

A key resource is to use

.https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference[Mozilla Developer reference]

In a date object the month is always zero based

Use getFullYear instead of getYear

If you need to compare two dates use the Date.getTime() function to ensure you compare
the millisecond values, as oppose to comparing the Date objects which would be different references.

The innerHtml method on the document object can be useful to get the text content
from simple DOM elements (h1, p tags). For Div tags you can get more than just text.

[[direct access to DOM]]
[source, javascript]
.app.js
----
var myElem = document.createElement("li") // or p or div tags or whatever
----

Creates the element in space

then you need to add it to the DOM, or insert it.

myUl.appendChild(myElem);

then createTextNode and appendChild to myElem.

Event handler and event listener is the same

=== Timer functions

setTimeOut(message: String, time: millisecond) // only happens once
setInterval(message: String, time: millisecond) // happens every time

to stop a interval use the clearInterval method passing in a reference (handle) to the
original setInterval method (its return value)

# Common Errors

Have firebug open

To quickly control flow in a onSubmit event handler, run an if else and
if false then return false // prevents form from submitting data

else return true and passes data to server.

Consider using progressive enhancement by building your CSS styling into your
javascript file.

i.e. use document.getElementById("somediv").style.display = "block" || "none"

or use myElement.className = "someclass in CSS file" or set it to "" to clear

ALTERNATIVELY

Use jQuery addClass or removeClass which stacks classes.



Use the google closure compiler for minification

Use JSLint for code quality control

=== Javascript libraries

Google closure
Moo tools
Yahoo YUI
Dojo Toolkit
jQuery
Lightbox
Curvy corners

alternatively go to code.google.com/apis/libraries

TIP: Top tip: When using the CDN links start it with // as oppose to the protocol http or https
this way the browser uses whatever protocol it is already using.

Use feature detection
Modernizer is a great library for this

Use 
```
"use strict";
```
at top of all js files

var myRe = /hello/ is the same as new RegExp("hello") for regular expressions.
var mystring = "hello is in here"
if (myRe.test(myString)) { return true}


Resizing screen size

use window.onResize and check if it is small then change the link href
to a different CSS

Progressive enhancement allows you to create usable sites


=== ES6 Pitfalls 

Be careful when using the new for (let x in []) array. In the new syntax when you loop over an array
it adds the ordinal values and not the actual values expected.

function addPonies(...ponies) {
  let myponys = [];
  for (let pony in ponies) {
    myponys.push(pony);
  }
  return myponys;
}

console.log(addPonies("Penny","Stardust","Grizzler" )) // ["0","1","2"]

// but classic for loop works

function addPonies(...ponies) {
  let myponys = [];
  for (let i = 0; i < ponies.length; i++) {
    myponys.push(ponies[i]);
  }
  return myponys;
}

console.log(addPonies("Penny","Stardust","Grizzler" )) // ["Penny","Stardust","Grizzler"]


=== Handling Events

When dealing with Mouse coordinates ensure you use the new canvas api method

    // necessary to take into account CSS boudaries
    var rect = canvas.getBoundingClientRect();
