== Top tips for using Scala effectively.

===== HASHCODE AND EQUALS SHOULD ALWAYS BE PAIRED 
The equals and hashCode methods should always be implemented such that if x == y then x.+++## == y.+++##.

Stick to the following constraints when implementing equality:

. If two objects are equal, they should have the same hashCode.
. A hashCode computed for an object won’t change for the life of the object.
. When sending an object to another JVM, equality should be determined using
 attributes available in both JVMs.
. Utilize only immutable object internal state in hashCode computation
. Use default concepts for equals and hashCode

As you can see, this means that something in the object must be immutable. Making the entire object immutable simplifies this whole process greatly.

===== Use annotations to help with Scala optimizations
1. @tailrec
2. @switch

Usage: 

```scala
import annotation.switch

def check(x: Int) = 
  (x: @switch) match {
    case 1 => "One"
    case 2 => "Two"
    case x: Int => "Other"
  }

```

====== To optimize tail calls, the Scala compiler requires the following:
1. The method must be final or private: It can’t be polymorphic.
2. The method must have its return type annotated.
3.  The method must call itself as the “end” of one of its branches.

====== Compiler Magic

Use the following command when compiling to get a print out of how the compiler works

```scala 
-Xprint:parse
```


=== SBT

Use the SBT `reload` command within the SBT console when you make any dependency changes
to your `build.sbt` file

# Scala best practices

*80/20 rule * : 
write 80% of your program using pure functions (the “cake”), then create a 20% layer of other code on top of the functional base (the “icing”) to
handle the user interface, printing, database interactions, and other methods that have “side effects”.

