

== Principles

``Software entropy of the system increases over a period of time unless it is refactored``


http://www.laputan.org/mud/

=== Clean code

keeping your code clean is not just cost effective; it’s a matter of
*professional survival*.

[verse, Ron Jeffries, on clean code] 
Reduced duplication, high expressiveness, 
and early building of simple abstractions.
That’s what makes clean code for me.

== good practices
=== Method, Variable, Function, Interface, trait naming 
1. Use intention-revealing names
2. Avoid disinformation
3. Make meaningful distinctions
4. Use pronounceable names
5. Pick one word per concept
6. Add meaningful context
7. Classes and objects should have noun or noun phrase names
8. Methods should have verb or verb phrase names


=== Functions
1. keep it small (2-3 lines)
2. Do one thing
3. One level of abstraction per function
4. Apply the stepdown rule consistently
5. Avoid passing boolean arguments, rather seperate function into two
6. Keep arguments to one, two at most for functions
7. Prefer Exceptions to Returning Error Codes

`In the case of a monadic function, the function and argument should form a very nice verb/noun pair.`



=== Microservices

Microservices vs Monoliths
http://blog.arungupta.me/microservices-monoliths-noops/

Design patterns
http://blog.arungupta.me/microservice-design-patterns/

=== Guidelines on testing code 

One particularly good method to start using thrid party APIs in your code base is to use them in *Learning Tests*. 
These are normal tests which essentially start interacting with the api, but in ways you would expect. This allows you
to quickly find out the lmitations in how it might solve some of your problems.

== the three laws of TDD
---

. *First law* You may not write production code until you have written a failing unit test.
. *Second law* You may not write more of a unit test than is sufficient to fail, and not compiling
is failing.
. *Third law* You may not write more production code than is sufficient to pass the currently
failing test.

> These three laws lock you into a cycle that is perhaps thirty seconds long. The tests
and the production code are written together, with the tests just a few seconds ahead of the
production code.

The usual approach to writing Unit tests is to *BUILD-OPERATE-TEST* with `One assert per test`

[verse, Kent Beck, a design is “simple” if it follows these rules]
. Runs all the tests
. Contains no duplication
. Expresses the intent of the programmer
. Minimizes the number of classes and methods
 

=== class organization
. Classes should be small

[Blockquote]
.class should begin with a list of variables. Public static constants, if any, should come first. Then private static variables, followed by private
instance variables. There is seldom a good reason to have a public variable.

.Public functions should follow the list of variables. We like to put the private utilities
called by a public function right after the public function itself. This follows the stepdown
rule and helps the program read like a newspaper article.

== Systems design 

. Separation of concerns (AOP concept)
. Dependency Injection (inversion of control)


=== Programming laws

. Law of demeter
. Liskov substitution principle

=== General principles
. *principle of least privilege*  - If you don’t need to name it anywhere else, you needn’t.

=== General tips

.write in the language you are writing in




==== Abstraction

Properties that a system should have to best support the principle of abstraction?

. Encapsulation. It should be possible to hide the internals of a part.
. Compositionality. It should be possible to combine parts to make a new
part.
. Instantiation/invocation. It should be possible to create many instances
of a part based on a single definition. These instances “plug” themselves
into their environment (the rest of the system in which they will live) when
they are created.

==== Concurrency

For the programmer, there are four main practical approaches to writing concurrent
programs.

Taken from the CTMCP book by Peter van Roy

. *Sequential programming* (Chapters 3, 6, and 7). This is the baseline
approach that has no concurrency. It can be either eager or lazy.
. *Declarative concurrency* (Chapter 4). This is concurrency in the declarative
model, which gives the same results as a sequential program but can
give them incrementally. This model is usable when there is no observable
nondeterminism. It can be either eager (data-driven concurrency) or lazy
(demand-driven concurrency).
. *Message-passing concurrency* (Chapter 5 and Section 7.8). This is message
passing between port objects, which are internally sequential. This
limits the number of interleavings. Active objects (Section 7.8) are a variant
of port objects where the object’s behavior is defined by a class.
. *Shared-state concurrency* (this chapter). This is threads updating shared
passive objects using coarse-grained atomic actions. This is another approach
to limit the number of interleavings.


=== Turing Complete

The ability to define functions, to use function composition and recursion, and that 
has a conditional statement, is a complete programming language.  
We say it is *Turing complete*, which means that it can compute all the functions that a 
Turing machine can compute.