

== Principles

Software entropy of the system increases over a period of time unless it is refactored


http://www.laputan.org/mud/

=== Clean code

keeping your code clean is not just cost effective; it’s a matter of
*professional survival*.

[verse, Ron Jeffries, on clean code] 
Reduced duplication, high expressiveness, 
and early building of simple abstractions.
That’s what makes clean code for me.

== good practices
=== Method, Variable, Function, Interface, trait naming 
1. Use intention-revealing names
2. Avoid disinformation
3. Make meaningful distinctions
4. Use pronounceable names
5. Pick one word per concept
6. Add meaningful context
7. Classes and objects should have noun or noun phrase names
8. Methods should have verb or verb phrase names


=== Functions
1. keep it small (2-3 lines)
2. Do one thing
3. One level of abstraction per function
4. Apply the stepdown rule consistently



=== Microservices

Microservices vs Monoliths
http://blog.arungupta.me/microservices-monoliths-noops/

Design patterns
http://blog.arungupta.me/microservice-design-patterns/
